export type GitHubUser ={
    avatar_url: string
    bio: any
    blog: string
    company: any
    created_at: string
    email: any
    events_url: string
    followers: number
    followers_url: string
    following: number
    following_url: string
    gists_url: string
    gravatar_id: string
    hireable: any
    html_url: string
    id: number
    location: any
    login: string
    name: any
    node_id: string
    organizations_url: string
    public_gists: number
    public_repos: number
    received_events_url: string
    repos_url: string
    site_admin: boolean
    starred_url: string
    subscriptions_url: string
    twitter_username: any
    type: string
    updated_at: string
    url: string
    user_view_type: string
}